name: E2E Smoke & Coverage

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  smoke-e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate Prisma client
        run: npx prisma generate
      - name: Run smoke (@critical) Playwright tests
        run: npx playwright test -c playwright.smoke.config.ts
      - name: Merge coverage & enforce thresholds
        run: npm run coverage:check